def sonarproject = 'example-nodejs-app'
def sonarkey = '08f65dfd2e9957f27ae3d5aed4714651c5fb6f88'
def sonarhost = 'http://127.0.0.1:9000'


pipeline {
    agent any

    stages {

        stage('Clear') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git([url: "https://github.com/spy86/CI_CD.git", branch: 'main', credentialsId: '70150275-3513-4731-82e5-46abe898117e	'])
            }
        }
        stage('Run Sonarqube') {
            steps {
            dir('example-nodejs-app/App'){
            sh "/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=${sonarproject} -Dsonar.sources=. -Dsonar.host.url=${sonarhost} -Dsonar.login=${sonarkey}"
                }
            }
        }
        stage('Build Image and deploy') {
            steps {
            dir('example-nodejs-app/App'){
            sh "docker-compose up --force-recreate --build -d"
            sh "docker image prune -f"
                }
            }
        }
        stage('Check Service') {
            steps {
            dir('example-nodejs-app/App'){
            sh "docker-compose ps"
                }
            }
        }
    }
}