def sonarproject = 'example-nodejs-app'
def sonarhost = 'http://127.0.0.1:9000'


pipeline {
    agent any

    stages {

        stage('Clear') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git([url: "https://github.com/spy86/CI_CD.git", branch: 'main', credentialsId: 'github'])
            }
        }
        stage('Run Sonarqube') {
            steps {
            dir('example-nodejs-app/App'){
            withCredentials([string(credentialsId: 'sonarkey', variable: 'sonarkey')]) {
                sh "/opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=${sonarproject} -Dsonar.sources=. -Dsonar.host.url=${sonarhost} -Dsonar.login=${sonarkey}"
                }    
              }
            }
        }
        stage('Build Image and deploy') {
            steps {
            dir('example-nodejs-app/App'){
            sh "docker-compose up --force-recreate --build -d"
            sh "docker image prune -f"
                }
            }
        }
        stage('Check Service') {
            steps {
            dir('example-nodejs-app/App'){
            sh "docker-compose ps"
                }
            }
        }
    }
}