---
- hosts: target
  become: yes
  become_user: root
  tasks:

  - name: Import the jenkins apt key
    apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      state: present
    become: true

  - name: Add Jenkins apt repository entry
    apt_repository:
      repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
      state: present
    become: true

  - name: Ansible apt install ca-certificates
    apt:
      name: ca-certificates
      state: present

  - name: Update and apt packages
    apt:
      upgrade: no
      update_cache: yes
      cache_valid_time: 86400 

  - name: Ansible apt install default-jre
    apt:
      name: default-jre
      state: present

  - name: Ansible apt install jenkins
    apt:
      name: jenkins
      state: present

  - name: Ensure jenkins is installed
    apt: name=jenkins update_cache=yes
    become: yes

  - name: Ensure jenkins is running
    service: name=jenkins state=started