pipeline {
  environment {
    imagename = "${IMAGE_NAME}"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Checkout repository') {
      steps {
        git([url: 'https://github.com/spy86/docker-dart.git', branch: 'main'])

      }
    }
    stage('Building docker image') {
      steps{
        script {
          dockerImage = docker.build imagename
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
         sh "docker rmi $imagename:latest"

      }
    }
  }
    post {
        success {
                slackSend color: "good", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was successful. More info in this URL ${env.BUILD_URL}"
        }
        failure {
                slackSend color: "danger", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was failed. More info in this URL ${env.BUILD_URL}"
        }
        unstable {
                slackSend color: "warning", message: "Job: ${env.JOB_NAME} with buildnumber ${env.BUILD_NUMBER} was unstable. More info in this URL ${env.BUILD_URL}"
        }
    }
}